package com.sithumud.pos_backend.inventory.entity;

import com.sithumud.pos_backend.auth.entity.User;
import com.sithumud.pos_backend.branch.entity.Branch;
import com.sithumud.pos_backend.common.entity.BaseEntity;
import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.Index;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotBlank;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.Instant;
import java.util.ArrayList;
import java.util.List;

/**
 * Represents an inter-branch stock transfer request.
 *
 * When a transfer moves to COMPLETED, two {@link StockMovement} records are
 * created per line item: a TRANSFER_OUT on the source branch and a TRANSFER_IN
 * on the destination branch, both referencing this transfer's {@code transferNumber}.
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Entity
@Table(name = "stock_transfers", indexes = {
        @Index(name = "idx_transfer_number", columnList = "transfer_number", unique = true)
})
public class StockTransfer extends BaseEntity {

    /**
     * Human-readable, unique identifier generated by the service layer.
     * Example: "TRF-0338". Immutable once created.
     */
    @NotBlank
    @Column(name = "transfer_number", nullable = false, unique = true, length = 20)
    private String transferNumber;

    /** Branch sending the stock. */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "from_branch_id", nullable = false)
    private Branch fromBranch;

    /** Branch receiving the stock. */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "to_branch_id", nullable = false)
    private Branch toBranch;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    @Builder.Default
    private TransferStatus status = TransferStatus.IN_TRANSIT;

    /** Free-text reason for the transfer. Example: "Cover weekend shortfall". */
    @Column(columnDefinition = "TEXT")
    private String note;

    /**
     * When the destination branch confirmed full receipt.
     * Null until the transfer reaches COMPLETED status.
     */
    @Column(name = "completed_at")
    private Instant completedAt;

    /** User who initiated the transfer request. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "created_by")
    private User createdBy;

    @OneToMany(mappedBy = "transfer", cascade = CascadeType.ALL, orphanRemoval = true)
    @Builder.Default
    private List<StockTransferItem> items = new ArrayList<>();

    public void addItem(StockTransferItem item) {
        items.add(item);
        item.setTransfer(this);
    }
}
