package com.sithumud.pos_backend.sales.entity;

import com.sithumud.pos_backend.auth.entity.User;
import com.sithumud.pos_backend.branch.entity.Branch;
import com.sithumud.pos_backend.common.entity.BaseEntity;
import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.Index;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotBlank;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Entity
@Table(name = "sales", indexes = {
        @Index(name = "idx_sale_receipt_number", columnList = "receipt_number", unique = true)
})
public class Sale extends BaseEntity {

    /**
     * Human-readable receipt / transaction number generated by the service.
     * Example: "SALE-10493". Printed on customer receipts.
     * Immutable once set.
     */
    @NotBlank
    @Column(name = "receipt_number", nullable = false, unique = true, length = 20)
    private String receiptNumber;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "branch_id", nullable = false)
    private Branch branch;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "cashier_id", nullable = false)
    private User cashier;

    /**
     * Identifier of the physical POS terminal that processed the sale.
     * Used for per-terminal reconciliation and anomaly detection.
     * Nullable — web-based back-office sales have no terminal.
     */
    @Column(name = "terminal_id", length = 50)
    private String terminalId;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    @Builder.Default
    private SaleStatus status = SaleStatus.COMPLETED;

    /**
     * The actual time the transaction was completed at the POS terminal.
     * May differ from {@code createdAt} for offline sales synced after reconnect.
     */
    @Column(name = "sold_at", nullable = false)
    private Instant soldAt;

    /** Sum of all line totals before discount and tax are applied. */
    @Column(nullable = false, precision = 12, scale = 2)
    private BigDecimal subtotal;

    /** Total discount applied to the sale as a whole (not per-line discounts). */
    @Column(nullable = false, precision = 12, scale = 2)
    @Builder.Default
    private BigDecimal discount = BigDecimal.ZERO;

    /** Total tax amount included in the final total. */
    @Column(nullable = false, precision = 12, scale = 2)
    @Builder.Default
    private BigDecimal tax = BigDecimal.ZERO;

    /** Final amount charged to the customer (subtotal − discount + tax). */
    @Column(nullable = false, precision = 12, scale = 2)
    private BigDecimal total;

    /** Optional free-text note added by the cashier at point of sale. */
    @Column(columnDefinition = "TEXT")
    private String note;

    /**
     * Idempotency key set by the POS client so that a retried sync after a
     * network interruption can never be applied twice.
     */
    @Column(name = "idempotency_key", unique = true)
    private String idempotencyKey;

    @OneToMany(mappedBy = "sale", cascade = CascadeType.ALL, orphanRemoval = true)
    @org.hibernate.annotations.Fetch(org.hibernate.annotations.FetchMode.SUBSELECT)
    @Builder.Default
    private List<SaleItem> items = new ArrayList<>();

    /**
     * Payment legs for this sale.
     * A SPLIT payment is modelled as two Payment rows (one CASH, one CARD).
     */
    @OneToMany(mappedBy = "sale", cascade = CascadeType.ALL, orphanRemoval = true)
    @org.hibernate.annotations.Fetch(org.hibernate.annotations.FetchMode.SUBSELECT)
    @Builder.Default
    private List<Payment> payments = new ArrayList<>();

    public void addItem(SaleItem item) {
        items.add(item);
        item.setSale(this);
    }

    public void addPayment(Payment payment) {
        payments.add(payment);
        payment.setSale(this);
    }
}